navikt/crm-hot-tolk

force-app/main/default/flexipages/HOT_Request_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Service_Appointment_Record_Page.flexipage-meta.xml

https://jira.adeo.no/browse/TOLK-1649

TOLK-1649: Reduser tilgang til vedlegg for tolker --> master

---

force-app/main/default/objects/HOT_Request__c/fields/Subject__c.field-meta.xml

Utvidet Subject__c ("Tema"-feltet) til 255 tegn fra 100 tegn.
WO/WOLI/SA er allerede satt opp med 255 tegn på Subject__c.
https://jira.adeo.no/browse/TOLK-1654

TOLK-1654 --> master

---

force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.html
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/userCommunity/lwc/hot_requestList/hot_requestList.html
force-app/main/userCommunity/lwc/hot_requestList/hot_requestList.js

https://jira.adeo.no/browse/TOLK-1608

updated Mobile sorting for all lists

---

force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.html
force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html

https://jira.adeo.no/browse/TOLK-1608

Byttet ut picklist for sortering på mobil --> master

---

force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.html
force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.js

reset input's value on deleting uploaded file so that same file can be uploaded again

TOLK-191 small fix 

---

force-app/main/default/objectTranslations/HOT_WageClaim__c-no/Information__c.fieldTranslation-meta.xml
force-app/main/default/objectTranslations/HOT_WageClaim__c-no/ServiceResourceAddress__c.fieldTranslation-meta.xml
force-app/main/default/objectTranslations/HOT_WageClaim__c-no/ServiceResourceMobile__c.fieldTranslation-meta.xml
force-app/main/default/objects/HOT_WageClaim__c/fields/Information__c.field-meta.xml
force-app/main/default/objects/HOT_WageClaim__c/fields/ServiceResourceAddress__c.field-meta.xml
force-app/main/default/objects/HOT_WageClaim__c/fields/ServiceResourceMobile__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Saksbehandler.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1688

Wage claim (2) --> master

---

force-app/main/freelanceCommunity/lwc/hot_freelanceProfileWrapper/hot_freelanceProfileWrapper.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.js
force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.html
force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.js
force-app/main/userCommunity/lwc/hot_home/hot_home.html
force-app/main/userCommunity/lwc/hot_home/hot_home.js
force-app/main/userCommunity/lwc/hot_myWorkOrders/hot_myWorkOrders.html
force-app/main/userCommunity/lwc/hot_myWorkOrders/hot_myWorkOrders.js
force-app/main/userCommunity/lwc/hot_requestList/hot_requestList.html
force-app/main/userCommunity/lwc/hot_requestList/hot_requestList.js
force-app/main/userCommunity/lwc/hot_userContactInformation/hot_userContactInformation.html
force-app/main/userCommunity/lwc/hot_userContactInformation/hot_userContactInformation.js
force-app/main/userCommunity/lwc/hot_userInformation/hot_userInformation.html
force-app/main/userCommunity/lwc/hot_userInformation/hot_userInformation.js

https://jira.adeo.no/browse/TOLK-1693

Community cleanup links, navigation, img

---

force-app/main/userCommunity/lwc/hot_home/hot_home.html

https://jira.adeo.no/browse/TOLK-1599

TOLK-1599: changed links to kunnskapsbanken --> master

---

force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
force-app/main/sms/classes/HOT_SMSStatusChangeServiceBatch.cls

https://jira.adeo.no/browse/TOLK-1740

TOLK-1740 - SMS for statusoppdatering kobles til bruker og ikke bestiller

---

force-app/main/default/lwc/hot_fieldLabels/hot_fieldLabels.js
force-app/main/freelanceCommunity/classes/HOT_MyServiceAppointmentListController.cls

https://jira.adeo.no/browse/TOLK-1751

TOLK-1751: Added Description field to mySA list details --> master

---

force-app/main/default/objects/HOT_Request__c/validationRules/NumericPhone.validationRule-meta.xml

https://jira.adeo.no/browse/TOLK-1752

TOLK-1752: OrdererPhone validation rule --> master

---

force-app/main/default/globalValueSets/HOT_InterpreterStatus.globalValueSet-meta.xml
force-app/main/default/objects/HOT_Request__c/fields/ExternalRequestStatus__c.field-meta.xml
force-app/main/fslStatusTransition/classes/HOT_FieldServiceStatusHandlerTest.cls
force-app/main/fslStatusTransition/classes/HOT_RequestStatusHandler.cls
force-app/main/fslStatusTransition/classes/HOT_WorkOrderToRequestStatusTest.cls
force-app/main/fslStatusTransition/classes/HOT_WorkOrderToRequestStatusTest.cls-meta.xml
force-app/main/userCommunity/lwc/hot_requestList/hot_requestList.js

https://jira.adeo.no/browse/TOLK-1742

TOLK-1742: Statusflyt WO - R --> master

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

https://jira.adeo.no/browse/TOLK-1697

TOLK-1697 --> master

---

force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1761

TOLK-1761: person.Age access (reports) --> Master

---

force-app/main/fslStatusTransition/classes/HOT_RequestStatusHandler.cls
force-app/main/fslStatusTransition/classes/HOT_WorkOrderToRequestStatusTest.cls

https://jira.adeo.no/browse/TOLK-1765

Fixed Statusflow WO --> R

---

force-app/main/default/classes/HOT_DatabaseOperations.cls

Endret fra with sharing til inherited sharing I HOT_DatabaseOperations
Nå kan tolkbruker laste opp vedlegg på egen sak etter at saken har fått tildelt tolk.
https://jira.adeo.no/browse/TOLK-1772

TOLK-1772 --> master

---

force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/triggers/classes/HOT_ServiceResourceHandler.cls

Tok to greier inn her.
1. @chfosli Fikset logikken som oppretter SR til å sette Domain felt. Ga tilgang til config og admin
2. @EirikFladby Oppdaterte filter-logikk slik at fellesoppdrag viser for hele landet.

Service resource domain + fellesoppdrag filter --> master

---

force-app/main/sms/classes/HOT_ReminderSMSService.cls

https://jira.adeo.no/browse/TOLK-1780

TOLK-1780: Application Logs Status SMS --> master

---

force-app/main/default/objects/Person__c/fields/HOT_Address__c.field-meta.xml
force-app/main/default/objects/ServiceResource/fields/HOT_Address__c.field-meta.xml

https://jira.adeo.no/browse/TOLK-1644

TOLK-1644: ResidentialPlace --> master

---

force-app/main/default/objects/HOT_InterestedResource__c/fields/IsThreeYearsOld__c.field-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/HOT_IsFortyfiveDaysOld__c.field-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/HOT_IsThreeYearsOld__c.field-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/IsFortyfiveDayOlds__c.field-meta.xml
force-app/main/freelanceCommunity/classes/HOT_InterestedResourcesListController.cls
force-app/main/freelanceCommunity/classes/HOT_MyServiceAppointmentListController.cls
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js

IR and SA older than three years are hidden for Freelance Interpreter. 
For SA older than 45 days, attached files are also hidden. 
https://jira.adeo.no/browse/TOLK-256

Tolk 256 --> master

---

force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput_validationRules.js

TOLK-1833: Forespørsler uten tidspunkt blir opprettet fra nav.no
https://jira.adeo.no/browse/TOLK-1833

TOLK-1833 

---

force-app/main/default/classes/HOT_UpdateShiftsController.cls
force-app/main/default/flexipages/HOT_Shift_Record_Page.flexipage-meta.xml
force-app/main/default/lwc/updateShifts/updateShifts.html
force-app/main/default/lwc/updateShifts/updateShifts.js
force-app/main/default/objects/Shift/validationRules/HOT_ConnectToServiceResource.validationRule-meta.xml

https://jira.adeo.no/browse/TOLK-1863

Shift minor fixes --> master

---

force-app/main/default/objectTranslations/HOT_Request__c-no/Type__c.fieldTranslation-meta.xml
force-app/main/default/objects/HOT_Request__c/fields/Type__c.field-meta.xml

[TOLK-1858 - Endring av Type på Forespørsel](https://jira.adeo.no/browse/TOLK-1858)

TOLK-1858 - Endring av Type på Forespørsel

---

force-app/main/default/objects/HOT_Request__c/validationRules/RequireCompanyOnTPA.validationRule-meta.xml
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js
force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.js

https://jira.adeo.no/browse/TOLK-1877

TOLK-1877 - Får ikke sendt inn en bestilling der Anledning = Tolk på arbeidsplass - TPA

---

force-app/main/default/groups/HOT_Arkiv.group-meta.xml
force-app/main/default/layouts/ServiceTerritory-HOT Service Territory Layout.layout-meta.xml
force-app/main/default/queues/HOT_Arkiv.queue-meta.xml
force-app/scratch-org/layouts/ServiceResource-Service Resource Layout.layout-meta.xml

Opprettet ny kø og gruppe "HOT-Arkiv".
https://jira.adeo.no/browse/TOLK-1880

TOLK-1880 --> master

---

force-app/main/default/objects/WorkOrder/validationRules/HOT_DurationMax24Hours.validationRule-meta.xml

This reverts commit d1591e3ad816f81d27bf2b21c82eec262f387bcd.

Revert "Revert "Update HOT_DurationMax24Hours.validationRule-meta.xml""

---

force-app/main/default/classes/HOT_KrrCalloutQueuable.cls

https://jira.adeo.no/browse/TOLK-1892

TOLK-1892 - Oppdateringer fra KRR feiler

---

force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.css
force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js
force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls
force-app/main/userCommunity/lwc/hot_home/hot_home.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js

Tolk 1885 - Tilbakemeldinger

---

force-app/main/default/classes/HOT_KrrCalloutQueuable.cls
force-app/main/default/classes/HOT_KrrErrorBatch.cls
force-app/main/default/classes/HOT_KrrErrorBatch.cls-meta.xml
force-app/main/default/classes/HOT_KrrErrorBatchTest.cls
force-app/main/default/classes/HOT_KrrErrorBatchTest.cls-meta.xml
force-app/main/default/objects/Person__c/fields/HOT_IntegrationErrorCounter__c.field-meta.xml
force-app/main/default/objects/Person__c/fields/HOT_KrrIntegrationErrorCounter__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/triggers/classes/HOT_RequestHandler.cls

Lagt til counter field på Person og opprettet schedulable batch kjører retries.

Tolk 1892 - Oppdateringer fra KRR feiler

---

force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1853

TOLK - 1853 - Som ansatt-tolk skal jeg kunne se/redigere egen tjenesteressurs

---

force-app/main/default/objectTranslations/ServiceAppointment-no/HOT_DispatcherName__c.fieldTranslation-meta.xml
force-app/main/default/objects/HOT_InterestedResource__c/fields/Dispatcher__c.field-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/HOT_DispatcherName__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Frilans.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1839

Permsets del pol + Dispatcher field 

---

force-app/main/default/objects/HOT_Request__c/fields/PaymentLiability__c.field-meta.xml
force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls

https://jira.adeo.no/browse/TOLK-1920
See comment in jira

TOLK-1920 review: Blank out fields that should not be shown --> master

---

force-app/main/default/customMetadata/Deletion_Policy.HOT_DeleteFilesFromRequest.md-meta.xml
force-app/main/default/customMetadata/Deletion_Policy.HOT_DeleteFilesFromServiceAppointment.md-meta.xml
force-app/main/default/customMetadata/Deletion_Policy.HOT_HideInterestedResource.md-meta.xml
force-app/main/default/customMetadata/Deletion_Policy.HOT_HideRequest.md-meta.xml
force-app/main/default/customMetadata/Deletion_Policy.HOT_HideSMS.md-meta.xml
force-app/main/default/customMetadata/Deletion_Policy.HOT_HideServiceAppointment.md-meta.xml
force-app/main/default/customMetadata/Deletion_Policy.HOT_HideWorkOrder.md-meta.xml

https://jira.adeo.no/browse/TOLK-1841

TOLK-1841 - Opprett Deletion Policies med Record Mask Type

---

force-app/main/default/lwc/mineBestillingerWrapper/columns.js

https://jira.adeo.no/browse/TOLK-1950

Tolk 1950 - Legg til ikon for status "Åpen" i Mine Bestillinger/Bestillinger på vegne av andre

---

force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js

https://jira.adeo.no/browse/TOLK-1949
Viser seg at om man sender med en false parameter til NavigationMixin i state så blir den undefined, men kun om den er false...

Tolk 1949 - Når man avbryter å redigere/klone en bestilling blir man sendt til mine bestillinger uansett hvor man kom fra

---

force-app/main/triggers/classes/HOT_RequestHandler.cls
force-app/main/triggers/classes/HOT_RequestHandlerTest.cls

https://jira.adeo.no/browse/TOLK-1941

Tolk 1941 - UserInterpretationMethod feltet på bestillingsskjema må sette verdien i Tolkemetode på Forespørsel

---

force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls

https://jira.adeo.no/browse/TOLK-1957

TOLK-1957 - Valg av fødselsnr/tlfnr bevares ikke ved kopiering av bestilling på vegne av bruker

---

force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls

https://jira.adeo.no/browse/TOLK-1959

TOLK-1959: Tolkebrukers navn vises for annen bestiller lengre enn en uke --> master

---

force-app/main/freelanceCommunity/classes/HOT_FreelanceQualificationsController.cls
force-app/main/freelanceCommunity/lwc/hot_freelanceProfileWrapper/hot_freelanceProfileWrapper.css
force-app/main/freelanceCommunity/lwc/hot_freelanceProfileWrapper/hot_freelanceProfileWrapper.html
force-app/main/freelanceCommunity/lwc/hot_freelanceProfileWrapper/hot_freelanceProfileWrapper.js
force-app/main/freelanceCommunity/lwc/hot_frilanstolkQualifications/hot_frilanstolkQualifications.css
force-app/main/freelanceCommunity/lwc/hot_frilanstolkQualifications/hot_frilanstolkQualifications.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkQualifications/hot_frilanstolkQualifications.js
force-app/main/freelanceCommunity/lwc/hot_frilanstolkUserInformation/hot_frilanstolkUserInformation.css
force-app/main/freelanceCommunity/lwc/hot_frilanstolkUserInformation/hot_frilanstolkUserInformation.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkUserInformation/hot_frilanstolkUserInformation.js

https://jira.adeo.no/browse/TOLK-1946 + refaktorering av kode

Tolk 1946 - Frilanstolker opplever at kvalifikasjoner blir nullet ut

---

force-app/main/accessControl/classes/HOT_RequestRoutingHandler.cls
force-app/main/default/objects/Person__c/fields/HOT_MobilePhoneStripped__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1852

TOLK-1852: Kobling til bruker via tlf nummer feiler --> master

---

force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js

https://jira.adeo.no/browse/TOLK-1895

Tolk 1895 - Bestillinger kommer inn uten dato og tidspunkt eller med feil tidspunkt

---

force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js

TOLK - 1895

---

force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput.js

https://jira.adeo.no/browse/TOLK-1956

TOLK - 1956 - Som bestiller ønsker jeg å kunne sende inn en bestilling som går over midnatt

---

force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.html
force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.html
force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.js

Added aria-live on loader and success on request order.
Added refresh of contentdocuments when editing request.

Aria and refresh files on edit

---

force-app/main/default/objectTranslations/ServiceAppointment-no/HOT_Interpreters__c.fieldTranslation-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/HOT_Interpreters__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Frilans.permissionset-meta.xml

TODO:
* Legge til felt på HOT Tolk Service Appointment Layout

TOLK-1927 --> master Frilanstolk skal se medtolk i FSL

---

scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

Revert "TOLK-1922 --> master Dialogrelaterte pakker"

---

force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls
force-app/main/default/classes/HOT_InterpreterOnWorkOrderServiceTest.cls
force-app/main/default/classes/HOT_UpdateExistingRecords.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls

Revert "Nightlyfix"

---

force-app/main/default/classes/HOT_KrrErrorBatch.cls
force-app/main/default/classes/HOT_KrrErrorBatchTest.cls

https://jira.adeo.no/browse/TOLK-1944

TOLK-1944 - KRR callouts feiler

---

scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

Revert "Revert "TOLK-1922 --> master Dialogrelaterte pakker""

---

force-app/main/default/objects/HOT_Request__c/validationRules/Account_cannot_be_edited.validationRule-meta.xml
force-app/main/default/objects/WorkOrder/validationRules/Account_cannot_be_edited.validationRule-meta.xml

Revert "TOLK-1974 - Endre valideringsregel som forhindrer formidler å endre bruker"

---

force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.css
force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js
force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js
force-app/main/userCommunity/lwc/hot_requestForm_company/hot_requestForm_company.css
force-app/main/userCommunity/lwc/hot_requestForm_company/hot_requestForm_company.html
force-app/main/userCommunity/lwc/hot_requestForm_orderer/hot_requestForm_orderer.css
force-app/main/userCommunity/lwc/hot_requestForm_orderer/hot_requestForm_orderer.html
force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.css
force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.html
force-app/main/userCommunity/lwc/hot_requestForm_user/hot_requestForm_user.css
force-app/main/userCommunity/lwc/hot_requestForm_user/hot_requestForm_user.html

https://jira.adeo.no/browse/TOLK-1983

TOLK-1983 - VoiceOver forbedring av tolkebestillingsløsningen

---

force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.js

https://jira.adeo.no/browse/TOLK-2025

TOLK-2025: Read By Nav --> master 

---

force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js

https://jira.adeo.no/browse/TOLK-2023

Tolk 2023 - Når bruker dobbelt-klikker på "Send inn" i bestillingsskjema opprettes det 2 forespørsler, hvor den andre av dem ikke har tidspunkt

---

force-app/main/userCommunity/classes/HOT_RequestListController.cls
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.html
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_requestFormWrapper.js

https://jira.adeo.no/browse/TOLK-2024

TOLK-2024 - Når bruker redigerer bestillingen mens formidler jobber på den, kan det oppståd feil i data

---

force-app/main/default/flexipages/HOT_Request_Record_Page.flexipage-meta.xml
force-app/main/default/objects/HOT_Request__c/fields/IsAccountNotNull__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/dialogue/classes/HOT_ThreadHandler.cls
force-app/main/dialogue/classes/HOT_ThreadHandlerTest.cls
force-app/main/dialogue/layouts/Thread__c-HOT Thread Layout.layout-meta.xml
force-app/main/dialogue/permissionsets/HOT_Dialog.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-2038

Dialog clean up

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/dialogue/classes/HOT_ThreadHandler.cls
force-app/main/dialogue/classes/HOT_ThreadHandlerTest.cls

moved setting of HOT request field to trigger

moved setting of HOT request field to trigger

---

force-app/main/default/permissionsets/HOT_Tolk_Bruker.permissionset-meta.xml
force-app/main/dialogue/classes/HOT_ThreadListController.cls
force-app/main/dialogue/permissionsets/HOT_Dialog.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-2068

TOLK-2068 --> master

---

force-app/main/default/classes/HOT_ProcessBuilderMigrationTest.cls
force-app/main/default/classes/HOT_ProcessBuilderMigrationTest.cls-meta.xml

https://jira.adeo.no/browse/TOLK-1897

TOLK-1897: Test class --> master

---

force-app/main/default/classes/HOT_Utility.cls

https://jira.adeo.no/browse/TOLK-479
Hei. Kan du ta en titt om denne endringen løser dette?

TOLK-479: Håndtere kode 6/7 brukere 

---

force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.css
force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2105
- Lagt til mulighet for å melde seg til alle oppdrag i serien inne på et oppdrag.

Frilanslist open series

---

force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2106

Fixed formatting

---

force-app/main/default/flexipages/Person_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/Person__c-HOT Person Layout.layout-meta.xml
force-app/main/default/lwc/hot_warningBannerAccount/hot_warningBannerAccount.html
force-app/main/default/lwc/hot_warningBannerAccount/hot_warningBannerAccount.js
force-app/main/default/lwc/hot_warningBannerRequest/hot_warningBannerRequest.html
force-app/main/default/lwc/hot_warningBannerRequest/hot_warningBannerRequest.js
force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
force-app/main/default/quickActions/Person__c.Update_Person.quickAction-meta.xml

https://jira.adeo.no/browse/TOLK-1069

implemented new structure for security measures

---

force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/filters.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.css

https://jira.adeo.no/browse/TOLK-2051

Search in filter

---

force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.js
force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js
scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

https://jira.adeo.no/browse/TOLK-2091

TOLK-2091: Behold detaljer-side på refresh

---

force-app/main/default/objects/ServiceAppointment/fields/HOT_AssignmentCategory__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Frilans.permissionset-meta.xml
force-app/main/freelanceCommunity/classes/HOT_OpenServiceAppointmentListController.cls
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/filters.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2103

Added filter on AssignmentCategory and fixed button

---

force-app/main/default/objects/HOT_WageClaim__c/fields/ServiceAppointmentCity__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Frilans.permissionset-meta.xml
force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.js
force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/wageClaim/classes/HOT_WageClaimListController.cls
force-app/main/wageClaim/lwc/hot_wageClaimList/columns.js
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.html
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js

https://jira.adeo.no/browse/TOLK-2000

TOLK-2000: Poststed på WageClaim-liste

---

force-app/main/default/objects/ServiceAppointment/fields/HOT_WOLIDatetimeOOS__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-2124

Out of sync field to use in filters

---

force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput.html
force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput.js

https://jira.adeo.no/browse/TOLK-2122

TOLK-2122: Feil i tidspunkt i bestillingskjema ved redigering

---

force-app/main/default/objects/Thread__c/compactLayouts/HOT_Thread_Compact_Layout.compactLayout-meta.xml

https://jira.adeo.no/browse/TOLK-2069

Tolk-2069 -> master Create HOT_Thread_Compact_Layout.compactLayout-meta.xml

---

force-app/main/triggers/classes/HOT_RequestHandler.cls
force-app/main/triggers/classes/HOT_RequestHandlerTest.cls

https://jira.adeo.no/browse/TOLK-1351

Tolk-1351 -> Master Update HOT_RequestHandler.cls

---

force-app/main/default/objectTranslations/Thread__c-no/HOT_IsMyThread__c.fieldTranslation-meta.xml
force-app/main/default/objects/Thread__c/fields/HOT_IsMyThread__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-2126

TOLK-2126: Is My Thread field

---

force-app/main/sms/classes/HOT_ReminderSMSService.cls

Mer luft https://jira.adeo.no/browse/TOLK-2003

Tolk-2003: Mer luft i Påminnelse sms

---

force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml

Etter det jeg kan se er det kun HOT_Tolk_Ansatt som kan ha sett dette feltet til nå. Er allerede avkrysset på HOT_Tolk_Frilans
https://jira.adeo.no/browse/TOLK-2127

Tolk 2127 - Jeg vil ikke se at noen foretrekker en annen tolk fremfor meg

---

force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

https://jira.adeo.no/browse/TOLK-2069

TOLK-2069: Thread Compact Layout

---

force-app/main/sms/flows/HOT_SendSMSToAccount.flow-meta.xml

https://jira.adeo.no/browse/TOLK-2135

Tolk 2135 - Hurtigtekst på sms

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.css
force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.html
force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.js

https://jira.adeo.no/browse/TOLK-2041

Tolk 2041 - gå til bestilling knapp på samtaler

---

force-app/main/default/classes/HOT_UpdateExistingRecords.cls

https://jira.adeo.no/browse/TOLK-2159
Henter alle personer som er tolkbrukere og setter HOT_NotificationChannel__c til SMS

Tolk 2159 - Oppdatere Notificationchannel til tolkbrukere til SMS

---

force-app/main/default/flexipages/HOT_Person_Account_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/HOT_Request__c-Request Layout.layout-meta.xml
force-app/main/default/objects/HOT_Request__c/fields/IsAccountEqualOrderer__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1709

Tolk 1709-Liste skal KUN ha forespørsler der account er bestiller

---

force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/userCommunity/classes/HOT_UserInformationController.cls
force-app/main/userCommunity/lwc/hot_tolketjenestenUserInformation/hot_tolketjenestenUserInformation.html
force-app/main/userCommunity/lwc/hot_tolketjenestenUserInformation/hot_tolketjenestenUserInformation.js

https://jira.adeo.no/browse/TOLK-2140

Tolk 2140 - Som tolkebruker ønsker jeg å kunne velge varslingskanal for mine varsler

---

force-app/main/default/objectTranslations/ServiceAppointment-no/HOT_WorkOrder__c.fieldTranslation-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/HOT_WorkOrder__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
force-app/scratch-org/layouts/ServiceAppointment-Service Appointment Layout.layout-meta.xml

https://jira.adeo.no/browse/TOLK-1618

Tolk 1618- v2 Lenke til arbeidsordre på oppdrag

---

force-app/main/default/layouts/Person__c-HOT Person Layout.layout-meta.xml
force-app/main/default/quickActions/Person__c.Update_Person.quickAction-meta.xml
force-app/main/userCommunity/lwc/hot_tolketjenestenUserInformation/hot_tolketjenestenUserInformation.html
force-app/main/userCommunity/lwc/hot_tolketjenestenUserInformation/hot_tolketjenestenUserInformation.js

https://jira.adeo.no/browse/TOLK-2140

removed from layouts and min-side page

---

force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/sms/flows/HOT_SendSMSToAccount.flow-meta.xml

https://jira.adeo.no/browse/TOLK-2176
Hilsen er endret til Mvh tolketjenesten i NAV

Tolk 2176 - Endre tekst etter mvh i sms som sendes ut

---

force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.js

https://jira.adeo.no/browse/TOLK-2165
**DETTE ER DEN STØRSTE OPPGAVEN JEG NOENSINNE HAR GJORT**
Lag en bestilling
Gå inn på bestillingen og trykk "Samtale med formidler"
Inne i samtalen så trykker du på "Mine bestillinger" i brødsmulelinken.
Så skal du komme til en side hvor du kommer tilbake til mine bestillinger

Tolk 2165 - fikser brødsmulestien 

---

force-app/main/default/layouts/SMS__c-HOT SMS Layout.layout-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

Se https://github.com/navikt/crm-platform-integration/pull/208 for testscript

Nytt felt recipientFormatted og layout

---

force-app/main/default/objectTranslations/ServiceAppointment-no/HOT_ResourceType__c.fieldTranslation-meta.xml
force-app/main/default/objects/ServiceAppointment/fields/HOT_ResourceType__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-1026

TOLK-1026: Type Tolk felt

---

force-app/main/default/flexipages/Interested_Resource_Record_Page.flexipage-meta.xml
force-app/main/default/objects/HOT_InterestedResource__c/HOT_InterestedResource__c.object-meta.xml
force-app/main/default/objects/HOT_InterestedResource__c/compactLayouts/HOT_Interested_Resource_Compact_Layout.compactLayout-meta.xml

https://jira.adeo.no/browse/TOLK-2162

Tolk 2162 - Endre IR compact layout

---

force-app/main/default/flows/HOT_ChangeServiceAppointmentStatus.flow-meta.xml

https://jira.adeo.no/browse/TOLK-1980

TOLK-1980:  ChangeServiceAppointmentStatus

---

force-app/main/default/flows/HOT_Shift_Before_Insert.flow-meta.xml
force-app/main/default/objects/Shift/fields/HOT_WageClaim__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
force-app/main/wageClaim/classes/HOT_WageClaimHandler.cls
scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac

https://jira.adeo.no/browse/TOLK-1890

TOLK-1890: Ledig på lønn i ressursplanlegger

---

force-app/main/default/classes/HOT_UpdateExistingRecords.cls
force-app/main/default/objects/HOT_Request__c/validationRules/Account_cannot_be_edited.validationRule-meta.xml
force-app/main/default/objects/ServiceAppointment/validationRules/Account_cannot_be_edited.validationRule-meta.xml
force-app/main/default/objects/WorkOrder/validationRules/Account_cannot_be_edited.validationRule-meta.xml

Må deaktivere valideringsreglene på F, AO, og SA.

Deaktivering av valideringsregler og UpdateExistingRecords

---

force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js

https://jira.adeo.no/browse/TOLK-1087
Påmeldte oppdrag - GOOD Hot_interestedResourcesList
**Mine oppdrag - GOOD hot_myServiceAppointments**
Ledige oppdrag -  GOOD(ifølge kode) Hot_openServiceAppointments
Ledig på lønn - GOOD(ifølge kode) Hot_wageClaimList
**Mine bestillinger - GOOD**
Tekst merket i tjukk skrift er de jeg har endret. Resten skal være i orden fra før, men det kan du også sjekke. Lag oppdrag slik at det kommer et oppdrag under hver liste og test. Gå i salesforce og endre på noe informasjon som vises i listevisningen. Gå på en annen liste, og tilbake, og da skal teksten være endret. 
Når det gjelder mine bestilinger listen. Gå inn på bestillingen, og tilbake, og teksten skal være endret.

Tolk 1087 - alle lister skal være oppdatert

---

force-app/main/default/lwc/hot_warningBannerAccount/hot_warningBannerAccount.html
force-app/main/default/lwc/hot_warningBannerAccount/hot_warningBannerAccount.js
force-app/main/default/lwc/hot_warningBannerRequest/hot_warningBannerRequest.html
force-app/main/default/lwc/hot_warningBannerRequest/hot_warningBannerRequest.js

https://jira.adeo.no/browse/TOLK-2170
**Hva:** 
Fikset feil i banner som gjorde at sikkerhetstiltak ikke kom opp. (json feil) På både bruker-siden og på forespørsel. 
**Test:**

Tolk 2170 - sikkerhetstiltak banner

---

force-app/main/default/objects/ServiceResource/fields/HOT_MoreInformation__c.field-meta.xml

https://jira.adeo.no/browse/TOLK-2186

Tolk 2186 - oppdatere hjelpetekst på mer informasjon

---

force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput.js
force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput_validationRules.js
force-app/main/userCommunity/lwc/hot_requestFormWrapper/hot_createRequestForm_validationRules.js

https://jira.adeo.no/browse/TOLK-2200

TOLK-2200 --> master Sluttid MÅ være ulike Starttid i bestillingsskjema

---

force-app/main/default/classes/HOT_InterestedResourceBannerController.cls

https://jira.adeo.no/browse/TOLK-2204

TOLK-2204 - ikke vise banner på interesert ressurs når det er tildelt

---

force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.html
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js

https://jira.adeo.no/browse/TOLK-2187

Tolk 2187-+1 -Som frilanstolk ønsker jeg å beholde posisjon på oppdragslisten

---

force-app/main/default/flows/HOT_MobileAppAccess.flow-meta.xml

Sjekker om bruker finnes - hvis ikke gis det beskjed om det og flyten ender på en mer brukervennlig måte.
For å teste:
1. Push til scratch (ligger allerede i UAT også, hvis dere vil teste der)
2. Setup -> Flow -> Finn flown
3. Debug - Velg en konto (Agder Bruker f.eks), PS: 0PS7U000000CaurWAC, og recordId: 0012o00002oXdT9AAK

TOLK-2216 --> master Update HOT_MobileAppAccess.flow-meta.xml

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.js

https://jira.adeo.no/browse/TOLK-2212
Knapp "Gå til bestilling" inne på mine samtaler fungerer ikke om man går fra Mine samtaler, trykker inn på en samtale, og deretter trykker "Gå til bestilling", men nå gjør den det. :)
Sjekk at den går til riktig oppdrag med både seriebestillinger og enkeltbestillinger

Tolk-2212 - Gå til bestilling knapp fix på samtale

---

force-app/main/triggers/classes/HOT_RequestHandler.cls
force-app/main/triggers/classes/HOT_RequestHandlerTest.cls

For å teste:
1. Klon en forespørsel og sjekk at Source/Kilde er tilsvarende i klonen.

TOLK-2213 --> master Update HOT_RequestHandler.cls

---

force-app/main/fslStatusTransition/classes/HOT_RequestStatusHandler.cls

https://jira.adeo.no/browse/TOLK-2227

TOLK-2227: Når man ender opp med bare avlyst og udekkede arbeidsordre på en forespørsel gir dette en feilmelding

---

force-app/main/freelanceCommunity/classes/HOT_MyServiceAppointmentListController.cls
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js

https://jira.adeo.no/browse/TOLK-1191
Hadde nådd maskimalt antall formelfelt

Tolk 1191 - Eksponere mobilnummer til bestiller for frilanstolker

---

force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.js

https://jira.adeo.no/browse/TOLK-2225

Tolk 2225 - Frilans beholder valgt liste ved refresh og åpner alltid "Ledige oppdrag" listen først

---

force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2111
Måtte bruke localstorage for at det skal være lagret når bruker trykker tilbake til forsiden også

Tolk 2111 - sjekkbokser blir ikke lenger borte når bruker refresher eller går tilbake til forsiden

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/notification/classes/HOT_UserNotificationServiceTest.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls

* Finn SA hvor bruker er testbrukeren din i Playground-appen
* Test med å tildele tolk (Fra åpen) og sjekk at du får varsel om tildelt tolk
* Uten å endre status, endre tolk og sjekk at du får varsel om endret tolk. 
* I begge tilfeller, sjekk at du kommer inn på bestillingen ved å klikke på varselet

TOLK-2196 --> master Push-varsel ved endring av tolk

---

force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/sms/classes/HOT_ReminderSMSBatch.cls

* Testet i uat ved å kjøre batch-jobben, HOT_ReminderSMSBatch.

TOLK-2198 --> master Lagt til Push-varsel ved påminnelse om bestilling

---

force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/filters.js

Revert "Update filters.js Ny status på filter"

---

force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2202

Tolk 2022 - frigitt idag filter knapp

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
force-app/main/sms/classes/HOT_SMSStatusChangeServiceBatch.cls
force-app/main/userCommunity/lwc/hot_requestForm_orderer/hot_requestForm_orderer.html

Fikset en feil som gjorde at notifikasjoner ble ufullstendige når ett oppdrag i et flertolksoppdrag ble satt til udekket.

Notification fix -> master

---

force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js

Sjekk at alle filterene lagres ved refresh og bytte på alle lister
Sjekk at når antall merkede checkboxer ikke matcher samme antall som vises på "Antall" i filteret så fjernes alle checkboxer. Og alle checkboxer fjernes når man trykker på "Frigitt idag"/"Fjern frigitt idag filter".

Filter og checkbox fix try nr 100

---

force-app/main/default/classes/HOT_Utility.cls
force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/sms/classes/HOT_ReminderSMSBatch.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls

* Endring av tolk går nå kun til bestiller, vs til bruker. 
* Bestillinger gjort av andre som ikke skulle varsle tolkebruker havnet ved en feil i Bestillinger på vegne av andre hos nettopp tolkebruker 😨

TOLK-2246 --> master Varsel til bestiller og bestillinger havnet i feil liste

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/dialogue/classes/HOT_MessageHelperTest.cls
force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.html
force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.js

Når du har oppe samtale komponenten eller når "formidler" åpner samtale fra liste vil du se hvem du snakker med (flere tolker, bruker, frilanstolk/tolk osv).

Se hvem som er i samtalen

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/dialogue/classes/HOT_ThreadListController.cls
force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.html
force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.js
force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.js

Prøv å opprett alle trådtypene.
Hjelpeteksten inne på samtalen skal endre seg basert på hvilken trådtype det er.
På mine samtaler listen vil du se når siste melding ble sendt. På eldre eksisterende tråder vil den eventuelt bare være tom.
Inne på samtalen vil det også stå hvem samtalen er mellom

Mer på dialog

---

force-app/main/default/classes/HOT_MessageHandler.cls
force-app/main/default/classes/HOT_MessagesNotification.cls

**GJORT:**
Varsel inneholder hvilken samtale det er.
Varsel blir ikke sendt til formidler når formidler sender melding
Varsler fra samtaler til formidlere blir kun sendt samtaler formidlere er en del av

Varsler formidlere

---

force-app/main/freelanceCommunity/classes/HOT_InterestedResourcesListController.cls

Hadde glemt ny tittel når ny tråd lages når meldes interesse

Ny tittel når ny tråd lages når meldes interesse

---

force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls
force-app/main/userCommunity/classes/HOT_WorkOrderListControllerTest.cls

samme som https://github.com/navikt/crm-hot/pull/1658/files

 try 2 :)))

---

force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js

Når popup lukkes skal disabled resettes

Forhindre at knappene forblir disablet om det skulle skje noe

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/triggers/classes/HOT_RequestHandler.cls
force-app/main/triggers/classes/HOT_RequestHandlerTest.cls

https://jira.adeo.no/browse/TOLK-2260 
Dette var ønske fra formidlere
Test:
* Når det finnes tråder fra før tilhørende et oppdrag, så skal Dispatcher feltet på thread endres til det samme som Dispatcher på forespørsel endres til.
* Når man oppretter en ny tråd så skal feltet på dispatcher få samme dispatcher som på forespørsel

TOLK-2260: Når Dispatcher på Forespørsel endres vil alle tråder (SA, IR, WO, R) tilhørende den forespørsel få samme Dispatcher

---

force-app/main/dialogue/classes/HOT_ThreadHandler.cls

https://jira.adeo.no/browse/TOLK-2264

Tolk 2264 - Legge på (...) når subject overgår lengde på Tråd

---

force-app/main/default/classes/HOT_MessageHandler.cls
force-app/main/default/classes/HOT_MessagehandlerTest.cls
force-app/main/default/classes/HOT_MessagesNotification.cls
force-app/main/dialogue/classes/HOT_MessageHelperTest.cls

https://jira.adeo.no/browse/TOLK-2263
Det er endringene på HOT_MessageHandler og HOT_MessagesNotification som fikser feilen.

TOLK-2263: Fikset opp i class modifiers på Message-klassene

---

force-app/main/sms/classes/HOT_ReminderSMSService.cls

Varsel til annen bestiller skal til nr oppgitt ved bestilling, ikke bestillers KRR-nummer.

TOLK-2266: Som bestiller ønsker jeg at nye meldinger fra formilder skal gå til nummeret oppgitt ved bestilling

---

force-app/main/default/flows/HOT_DeactivateFreelanceInterpreter.flow-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/scratch-org/layouts/ServiceResource-Service Resource Layout.layout-meta.xml

Se kommentar her: https://jira.adeo.no/browse/TOLK-2074

Tolk 2074 - deaktivere frilanstolker som ikke har logget på på over 1 år - v2

---

force-app/main/dialogue/classes/HOT_ThreadDetailController.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls

https://jira.adeo.no/browse/TOLK-2205
Når et oppdrag settes til Udekket eller Annullert, må status på interessert ressurs(er) endres til 
"Oppdrag tilbaketrukket"
TEST:
Alle IR som har status Interessert skal få status Oppdrag tilbaketrukket når oppdraget endrer status til avlyst eller udekket.

TOLK-2205 Statusendring på Interesserte ressurser

---

force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/userCommunity/classes/HOT_RequestListControllerTest.cls
force-app/main/userCommunity/classes/HOT_WorkOrderListControllerTest.cls

Tekst på SMS er endret. 
Hvis seriebestilling:
INFO
Det er bestilt tolk til deg i perioden: <datoStart> - <datoSlutt>
etc
Ellers
INFO
Det er bestilt tolk til deg:
Dato: <dato>
Klokkeslett: <klokkeslett>
etc

Ny SMS-tekst for andre bestillere --> master 

---

force-app/main/freelanceCommunity/classes/HOT_MyServiceAppointmentListController.cls
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/sms/classes/HOT_NotifyUserOnOrderServiceBatch.cls

Manuelle steg i prod:
Legg til google i CSP for å kunne laste inn kart

TOLK-2201 --> master Lagt til medtolk og betinget synlighet inne oppdragsdetaljer

---

force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.css
force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.css
force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.js

https://jira.adeo.no/browse/TOLK-2271

TOLK 2271 - Fjerne nedtrekk og fikse lister på mine samtaler frilans

---

force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/columns.js

TOLK 2271 : fjerner nye meldingsikonet fra mobil

---

force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2280

TOLK 2280 - Ikke kunne starte samtale med virksomhet

---

force-app/main/default/flows/HOT_RegisterWantedServiceResource.flow-meta.xml

Gir feilmelding om ikke oppdraget er frigitt til frilans først.
Og det er ikke mulig å sette flere enn en ønsket frilanstolk til hvert oppdrag

Oppdatert flow

---

force-app/main/freelanceCommunity/classes/HOT_InterestedResourcesListController.cls

https://jira.adeo.no/browse/TOLK-2284

TOLK 2284 - formidler legges nå på samtale fra ledige oppdrag listen

---

force-app/main/default/objects/HOT_InterestedResource__c/fields/Dispatcher__c.field-meta.xml

Må bruke dette feltet for nådd maksimum antall unike references
https://jira.adeo.no/browse/TOLK-2284

TOLK 2284 - navnet til formilder vises istedet for id på IR

---

force-app/main/default/notificationtypes/HOT_Wanted_ServiceResource.notiftype-meta.xml
force-app/main/freelanceCommunity/classes/HOT_WantedSRListControllerTest.cls
force-app/main/notification/classes/HOT_InterestedResourceNotification.cls
force-app/main/notification/classes/HOT_InterestedResourceNotification.cls-meta.xml
force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/triggers/classes/HOT_InterestedResourceHandler.cls
sfdx-project.json

https://jira.adeo.no/browse/TOLK-2294

TOLK-2294 - varsel til frilans ved ønsket til oppdrag

---

force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js

https://jira.adeo.no/browse/TOLK-2295

TOLK-2295: Bruker skal ikke kunne snakke med tolk før det er tildelt tolk

---

force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js

https://jira.adeo.no/browse/TOLK-2297
Plassering av knappene kan endres

TOLK-2297: Frilanstolker kan åpne adressen i google maps eller apple maps

---

force-app/main/default/flows/HOT_RegisterWantedServiceResource.flow-meta.xml
force-app/main/freelanceCommunity/classes/HOT_WantedSRListControllerTest.cls
force-app/main/freelanceCommunity/classes/HOT_wantedSRListController.cls
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.css
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.html
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.js
force-app/main/notification/classes/HOT_UserNotificationService.cls

https://jira.adeo.no/browse/TOLK-2298

TOLK-2298: Endringsønsker ønsket oppdrag liste

---

force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js

https://jira.adeo.no/browse/TOLK-2299

TOLK-2299 Bruker skal ikke kunne avlyse oppdraget om ikke han selv er bestiller

---

force-app/main/default/classes/HOT_MessagesNotification.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls

Nå får alle varsel på hot-bruker-tolk
Men ikke tolk-tolk. HVORFOR?! :((((

Varsel fix nr. 3

---

force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkServiceAppointmentLists/hot_frilanstolkServiceAppointmentLists.js
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.js

https://jira.adeo.no/browse/TOLK-2302
Om formidler registrerer ønsket oppdrag i en region som tolken ikke preferrerer blir oppdraget filtrert bort. Fjerner filteret helt i denne listen

TOLK-2302 - fjerner filtergreier på ønsket oppdrag liste

---

force-app/main/default/classes/HOT_MessageHandler.cls

Kommenterer ut nye uferdige varsler midlertidig

Kommenterer ut nye uferdige varsler midlertidig

---

force-app/main/default/objects/Thread__c/fields/HOT_AppointmentStartTime__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Annen_betaler.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_BetaUser.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Bruker.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Bruker_Plus.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Bruker_Plus_Login.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Frilans.permissionset-meta.xml
force-app/main/dialogue/classes/HOT_ThreadListController.cls
force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.js
force-app/main/dialogue/permissionsets/HOT_Dialog.permissionset-meta.xml
force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.js

https://jira.adeo.no/browse/TOLK-2304
Uleste samtaler øverst, deretter er samtalene sortert etter starttidspunkt for oppdraget for både frilans og brukere

TOLK-2304 : Sortering av samtaler etter startdato

---

force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.html
force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.js
force-app/main/freelanceCommunity/lwc/hot_freelanceTableListMobile/hot_freelanceTableListMobile.html
force-app/main/freelanceCommunity/lwc/hot_freelanceTableListMobile/hot_freelanceTableListMobile.js
force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.html
force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.js
force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.css
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html

Mobilvennlig tabell samtalister for frilans.
Mobilvennlig tabell samtalister for bruker.
Kan se når oppdraget starter på hver samtale.
Datoformatering med bare tall

Mer tabell for mobil

---

force-app/main/dialogue/classes/HOT_MessageHelper.cls
force-app/main/dialogue/classes/HOT_MessageHelperTest.cls
force-app/main/freelanceCommunity/classes/HOT_IRListControllerTest.cls
force-app/main/freelanceCommunity/classes/HOT_InterestedResourcesListController.cls
force-app/main/freelanceCommunity/classes/HOT_OpenServiceAppointmentListController.cls

https://jira.adeo.no/browse/TOLK-2305

TOLK-2305 : Unngår error ved for mange oppdrag og meldinger når man melder interesse

---

force-app/main/default/layouts/PersonAccount-HOT Tolk Person Account Layout.layout-meta.xml
force-app/main/default/objects/Event/compactLayouts/HOT_Event_Compact_Layout.compactLayout-meta.xml
force-app/main/default/objects/ServiceAppointment/compactLayouts/HOT_ServiceAppointment_Compact_Layout.compactLayout-meta.xml
force-app/main/default/objects/WorkOrder/compactLayouts/HOT_WorkOrder_Compact_Layout.compactLayout-meta.xml

Endringer på layout ihht ønsker beskrevet i https://jira.adeo.no/browse/TOLK-2307

Layouts Mobile App --> master

---

force-app/main/userCommunity/lwc/hot_home/hot_home.html
force-app/main/userCommunity/lwc/hot_userContactInformation/hot_userContactInformation.html

https://jira.adeo.no/browse/TOLK-2334

TOLK-2334 : oppdaterte lenker 

---

force-app/main/default/flexipages/Service_Appointment_Record_Page.flexipage-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-2307

TOLK 2307 : klargjøring av app

---

force-app/main/default/classes/HOT_CreateWorkOrderServiceTest.cls
force-app/main/dialogue/classes/HOT_MessageHelperTest.cls
force-app/main/freelanceCommunity/classes/HOT_NotificationCentreControllerTest.cls

97% createWorkOrderService
94% MessageHelper
100% NotificationHandler
Det som mangler er trycatch linjene, men de går jo ikke lage tester til

Mer tester

---

force-app/main/default/flows/HOT_ChangeServiceAppointmentStatus.flow-meta.xml
force-app/main/default/flows/HOT_RegisterWantedServiceResource.flow-meta.xml

HOT_ChangeServiceAppointmentStatus har fått validering på input av endtime > starttime
HOT_RegisterWantedServiceResource lagt til sjekk på hvorvidt SR er aktiv for å hindre nullpointer på not.ch

Flow changes --> master

---

force-app/main/default/flows/HOT_CreateFreelanceUser.flow-meta.xml

Komponentet som skal vise feilmelding sin conditinal-rendering knelet hele flowen.

Fikset en feil som knelet oppgrader bruker til frilans

---

force-app/main/default/classes/HOT_MessagehandlerTest.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls
force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls

96% messageHandler
88% remindersms

Mer test Halloween edition

---

force-app/main/default/classes/HOT_UpdateChildRecordsService.cls
force-app/main/default/classes/HOT_UpdateChildRecordsServiceTest.cls
force-app/main/default/flows/HOT_UpdateChildsFromRequest.flow-meta.xml

https://jira.adeo.no/browse/TOLK-2001

TOLK-2001 : Kunne endre tolkemetode på R,WO,WOLI,SA når man trykker på knapp "oppdater felter til oppdrag"

---

force-app/main/default/objects/ServiceAppointment/validationRules/Restrict_Dispatched_Status.validationRule-meta.xml

https://jira.adeo.no/browse/TOLK-1638

TOLK-1638  - Som formilder skal jeg ikke kunne endre status til tildelt/reservert om ikke det er satt på SR

---

force-app/main/default/objects/ServiceAppointment/validationRules/Restrict_Dispatched_Status.validationRule-meta.xml

This reverts commit 8f747b08b650df4c310655e8c9349c50917595f3, reversing changes made to f25f760729df9b65042154610e4a8f9b72372c17.

validation rule try #2

---

force-app/main/sms/classes/HOT_NotifyUserOnOrderServiceBatch.cls

La på serieoppdrag tekst på vsenteret ved serie

Update HOT_NotifyUserOnOrderServiceBatch.cls --> master

---

force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandlerTest.cls

Det er mulig ønskelig å ikke lenger sette ST lik PreferredResource sitt ST på SA.

Setter ikke tjenesteområde ved foretrukket tolk --> master

---

force-app/main/triggers/classes/HOT_RequestHandler.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
force-app/main/triggers/classes/HOT_WorkOrderLineItemHandler.cls
force-app/main/wageClaim/classes/HOT_CreateWageClaimTest.cls
force-app/main/wageClaim/classes/HOT_WageClaimServiceTest.cls

https://jira.adeo.no/browse/TOLK-2184
Vestland: Varsel om endring av medtolk: om en tolk tas av, er det ønskelig med varsel når det settes på ny medtolk til den som står igjen på det andre SA nummeret.

Tolk-2184 : Oppdrag mangler på virksomhet ved kloning

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/notification/classes/HOT_UserNotificationService.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls

https://jira.adeo.no/browse/TOLK-1218
Ansatttolk får ikke varsler her enda

TOLK-1218 - Frilanstolk/Tolk ønsker varsler når medtolk endres

---

.forceignore
force-app/main/default/classes/HOT_TestDataFactory.cls
force-app/main/triggers/classes/HOT_UserHandler.cls
force-app/main/triggers/classes/HOT_UserHandlerTest.cls
force-app/main/triggers/customMetadata/MyTriggerSetting.HOT_UserHandler_onAfterUpdate.md-meta.xml
force-app/scratch-org/profiles/HOT Tolk Ansatt.profile-meta.xml
force-app/scratch-org/profiles/HOT Tolk Formidler.profile-meta.xml

Bruker får nå opprettet SR når profil endres til Ansatt Tolk

Tolk 2301 - Opprette SR ved endring av formidler til ansatt tolk

---

force-app/main/default/flows/HOT_UpdateChildsFromRequest.flow-meta.xml

https://jira.adeo.no/browse/TOLK-2350

TOLK-2350 :  Feil i flow fiks

---

force-app/main/default/classes/HOT_AutoScheduleService.cls
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml

Manuelle steg i PROD: Rename policy "Auto schedule" --> "Ubegrenset"

Endret policynavn til Ubegrenset --> master

---

force-app/main/default/permissionsets/HOT_Tolk_Leder.permissionset-meta.xml

For de lederne som også skal ha tilgang til avvikssystemet, så må de settes opp en Login Flow for profilen HOT Tolk Leder. De må da ha tilgang til siden og kontrolleren.

NAV Kontor Login Flow

---

force-app/main/notification/classes/HOT_RequestNotification.cls

https://jira.adeo.no/browse/TOLK-2382

TOLK2382 - Feil med varsel til formidler når seriebestilling avlyses

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls

[TOLK-2389](https://jira.adeo.no/browse/TOLK-2389)

TOLK-2389 : Utvidet sms tekster

---

force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/columns.js

https://jira.adeo.no/browse/TOLK-2390

TOLK-2390 : Frilanstolker ønsker å se sa nummer på mobil

---

force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.html
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js

https://jira.adeo.no/browse/TOLK-2391
Fikser feilen som gjør at de ikke kunne trykke på knappen i app.

TOLK-2391 : Ny dialogboks for å få bekreftelse på ønske å tilbaketrekke tilgjengelighet på ledig på lønn liste

---

force-app/main/default/customMetadata/Deletion_Policy.HOT_DeleteNotification.md-meta.xml
force-app/main/default/objects/HOT_Notification__c/fields/DelPol_ToDeleteRecord__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml

https://jira.adeo.no/browse/TOLK-2346

TOLK-2346 - sletter eldre varsler

---

force-app/main/default/layouts/Person__c-HOT Person Layout.layout-meta.xml
force-app/main/dialogue/layouts/Thread__c-HOT Thread Layout.layout-meta.xml
force-app/scratch-org/layouts/ServiceResource-Service Resource Layout.layout-meta.xml

- Lagt til Owner på Thread
- Fikset et problem med Service Resource Layout som kom etter Winter '24 releasen
- Endret så Notification Channel er et påkrevt felt på Person

Endring på sideoppsett

---

force-app/main/default/classes/HOT_MessagesNotification.cls

https://jira.adeo.no/browse/TOLK-2421

TOLK-2421 : Ikke sende varsel til bruker som sendte meldingen

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/sms/classes/HOT_ReminderSMSService.cls

https://jira.adeo.no/browse/TOLK-2431

TOLK-2431 - endret sms

---

force-app/main/default/classes/HOT_UpdateExistingRecords.cls
force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml

Det er kun tolkenes bruker id'er som er i participants, men tolkebrukeres bruker id er i read by feltet.

Setter eksisterende tråder til lest av ansatt :)

---

force-app/main/default/objects/HOT_Request__c/fields/HOT_DelPol_ToHideRecord__c.field-meta.xml

Changed the formula to check the series end date first, if that is blank move on to End time, and if that is blank check generated date.

TOLK-2446 Update HOT_DelPol_ToHideRecord__c

---

force-app/main/default/objects/HOT_Request__c/fields/HOT_DelPol_ToDeleteFiles__c.field-meta.xml

Oppdaterte til å matche formel på HOT_DelPol_ToHideRecord__c

TOLK-2447 Update HOT_DelPol_ToDeleteFiles__c.field-meta.xml

---

force-app/main/default/objects/HOT_WageClaim__c/fields/MoreThan24HoursUntilStart__c.field-meta.xml
force-app/main/default/objects/HOT_WageClaim__c/listViews/Available_on_Wage.listView-meta.xml

New formula field on Lønnskrav and change in listview filter

New formula field on Lønnskrav and change in listview filte

---

force-app/main/default/objectTranslations/HOT_WageClaim__c-no/MoreThan24HoursUntilStart__c.fieldTranslation-meta.xml

oversettelse

---

force-app/main/dialogue/quickActions/Thread__c.HOT_Set_to_Redaction.quickAction-meta.xml

Set to redaction-->> Sett til sladding

change quick action label

---

force-app/main/dialogue/flexipages/HOT_Thread_Record_Page.flexipage-meta.xml

Change api name for action button

Thread record page

---

force-app/main/dialogue/flexipages/HOT_Thread_Record_Page.flexipage-meta.xml

Slett Sett til sladding fra HOT Thread record page

Slett action button

---

force-app/main/default/objects/HOT_Request__c/fields/HOT_DelPol_ToDeleteFiles__c.field-meta.xml

Changed deletionPolicy condition to also include the success field

Update HOT_DelPol_ToDeleteFiles__c.field-meta.xml- REQUEST

---

force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
force-app/main/triggers/classes/HOT_AssignedResourceHandlerTest.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls

Statuser: Avlyst av tolk, tilbaketrukket interesse, avslått

TOLK-2548 : Beholde status når oppdraget frigis på nytt om tolken har gjort et aktivt valg om ikke ønsker oppdraget

---

force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls

Får Påmeldt status når oppdraget frigis på nytt etter å ha vært tatt av oppdraget

---

force-app/main/default/flexipages/HOT_Request_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/Service_Appointment_Record_Page.flexipage-meta.xml
force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml

HOT_Tolk_Formidler permission set changed to give read access to deletion policy fields on Request, SA and Work Order objects

DeletionPolicy fields Read Access

---

force-app/main/default/flexipages/TiND_Mobile_Home.flexipage-meta.xml

* Fjernet to lister fra Hjem-skjerm

TOLK-2584 --> master Update TiND_Mobile_Home.flexipage-meta.xml

---

force-app/main/freelanceCalendar/lwc/hot_calendar/calendar_event.js
force-app/main/freelanceCalendar/lwc/hot_calendar/hot_calendar.js

Legger til egen visning for flerdagshendelser for mobiler. Hvor flerdagshendelser vises som en boks som strekker seg over dagene det gjelder på store skjermstørrelser vises en prikk for hver dag hendelsen gjelder på mobil.

Tolk 2614 mobilvisning av flerdagshendelser i kalender

---

force-app/main/notification/classes/HOT_IncomingSMSNotification.cls
force-app/main/triggers/classes/HOT_SMSHandler.cls

Legger til sjekk i SMSHandler på at type er inkommende og med HOT-domene

Fix on incoming SMS --> master 

---

force-app/main/freelanceCommunity/classes/HOT_FreelanceAbsenceController.cls

Setter Status korrekt og setter HOT_ServiceResource__c = null slik at Assigned Resource fjernes ordentlig fra SA

fikse feil hvor AssignedResource ikke fjernes korrekt

---

force-app/main/default/flexipages/Service_Appointment_Record_Page.flexipage-meta.xml

La til/fjernet felter som kom med forrige endring

Endret SA Record Page til å være slik den var før TOLK-2610 --> master

---

force-app/main/default/classes/HOT_UpdateExistingRecords.cls
force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls

* Varsel sendes ut for fremtidige oppdrag
* Nytt script for å endre adresse på oppdrag mellom 01/12/2021 - 01/12/2024

Varsel ved adresseendring og nytt script--> master

---

force-app/main/default/objects/ServiceAppointment/validationRules/RemoveARBeforeResettingStatus.validationRule-meta.xml

Added a condition to the Validation rule so that this only triggers if the Profile of the user is "HOT Tolk Formidler"

TOLK-2830: Update RemoveARBeforeResettingStatus.validationRule-meta.xml

---

force-app/main/default/classes/HOT_CreateWorkOrderServiceTest.cls
force-app/main/default/classes/HOT_ServiceAppointmentImageStatus.cls
force-app/main/default/classes/HOT_ServiceAppointmentImageStatusTest.cls
force-app/main/default/flexipages/HOT_Request_Record_Page.flexipage-meta.xml
force-app/main/triggers/classes/HOT_RequestHandler.cls
force-app/main/triggers/classes/HOT_RequestHandlerTest.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandlerTest.cls
force-app/main/triggers/classes/HOT_WorkOrderHandler.cls

* Bestiller navn skal være synlig selv om Orderer__c er tomt
* Lagt til Owner fra Req
* Lagt til oppdatering av owner/dispatcher fra SA ved oppdatering

TOLK-2872 --> master Oppdaterer relatert tråd med oppdatert Owner/Dispatcher fra R/SA

---

force-app/main/default/classes/HOT_UpdateExistingRecords.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandlerTest.cls

Manuelt steg: kjør updateexisting for å sette adressefelter N/A på bildetolkvakter

Fikser at adresse på bildetolkvakter ikke settes riktig --> master

---

force-app/main/freelanceCommunity/classes/lwc/hot_informationModal/hot_informationModal.js
force-app/main/freelanceCommunity/lwc/hot_freelanceTableListMobile/hot_freelanceTableListMobile.css
force-app/main/freelanceCommunity/lwc/hot_freelanceTableListMobile/hot_freelanceTableListMobile.html
force-app/main/freelanceCommunity/lwc/hot_interestedResourcesListModal/hot_interestedResourcesListModal.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointmentsModal/hot_openServiceAppointmentsModal.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointmentsModal/hot_openServiceAppointmentsModal.js
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsListModal/hot_wantedServiceAppointmentsListModal.js

Reverts navikt/crm-hot-tolk#2128

Fikser scroll i modal (Revert "TOLK-2667-scrollbare-lister-mobil")

---

force-app/main/freelanceCalendar/lwc/hot_calendar/hot_calendar.js
force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.js
force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js

Det er en bug på noen telefoner hvor man ikke kan krysse ut modalen. Salesforce pls fix.. hilsen Rasmus

Endre alle modal size til small

---

force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls

Og oppdaget at det ble sendt ut feil type sms når tolken ble tatt av. Rettet dette

TOLK-2915 : Varsel til tildelt tolk ved statusendring på SA til åpen (tas av oppdraget) v2

---

force-app/main/default/objects/HOT_Request__c/validationRules/Account_cannot_be_edited.validationRule-meta.xml

TOLK-3096: Fjern deaktiverte valideringsregler 

---

scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

oppdatert pakke versjoner etter dependency update

Oppdatere pakkeversjoner

---

force-app/main/facelift/lwc/hot_interestedResourcesList_v2/hot_interestedResourcesList_v2.css
force-app/main/facelift/lwc/hot_interestedResourcesList_v2/hot_interestedResourcesList_v2.html
force-app/main/facelift/lwc/hot_loader/hot_loader.css
force-app/main/facelift/lwc/hot_loader/hot_loader.html
force-app/main/facelift/lwc/hot_loader/hot_loader.js
force-app/main/facelift/lwc/hot_loader/hot_loader.js-meta.xml
force-app/main/facelift/lwc/hot_myRequestsWrapper/hot_myRequestsWrapper.css
force-app/main/facelift/lwc/hot_myRequestsWrapper/hot_myRequestsWrapper.html
force-app/main/facelift/lwc/hot_myRequestsWrapper/hot_myRequestsWrapper.js
force-app/main/facelift/lwc/hot_myServiceAppointmentsList_v2/hot_myServiceAppointmentsList_v2.css
force-app/main/facelift/lwc/hot_myServiceAppointmentsList_v2/hot_myServiceAppointmentsList_v2.html
force-app/main/facelift/lwc/hot_openServiceAppointmentsList_v2/hot_openServiceAppointmentsList_v2.css
force-app/main/facelift/lwc/hot_openServiceAppointmentsList_v2/hot_openServiceAppointmentsList_v2.html
force-app/main/facelift/lwc/hot_openServiceAppointmentsList_v2/hot_openServiceAppointmentsList_v2.js
force-app/main/facelift/lwc/hot_requestFormWrapper_v2/hot_requestFormWrapper_v2.css
force-app/main/facelift/lwc/hot_requestFormWrapper_v2/hot_requestFormWrapper_v2.html
force-app/main/facelift/lwc/hot_requestForm_company_v2/hot_requestForm_company_v2.css
force-app/main/facelift/lwc/hot_requestForm_orderer_v2/hot_requestForm_orderer_v2.css
force-app/main/facelift/lwc/hot_requestForm_request_v2/hot_requestForm_request_v2.css
force-app/main/facelift/lwc/hot_requestForm_user_v2/hot_requestForm_user_v2.css
force-app/main/facelift/lwc/hot_wageClaimList_v2/hot_wageClaimList_v2.css
force-app/main/facelift/lwc/hot_wageClaimList_v2/hot_wageClaimList_v2.html
force-app/main/facelift/lwc/hot_wantedServiceAppointmentsList_v2/hot_wantedServiceAppointmentsList_v2.css
force-app/main/facelift/lwc/hot_wantedServiceAppointmentsList_v2/hot_wantedServiceAppointmentsList_v2.html
force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.css
force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.css

Laget vår egen versjon av spinner/loader på aksel. Byttes ut med den gamle som vi har hatt og putter den på der det kan ta litt lang tid å laste for å unngå blank skjerm

TOLK-3161 : Spinner

---

force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls
force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls

Interpreters on WO is updated also when SA = Cannot complete.

TOLK-3176 --> master Adds check for 'Cannot Complete'

---

force-app/main/facelift/lwc/hot_recurringTimeInput_v2/hot_recurringTimeInput_v2.html

There are also additional changes on the input component in crm-community-base.

TOLK-3185 Date field size formatting on mobile
