- force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.css
- force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.html
- force-app/main/userCommunity/lwc/hot_createRequestForm/hot_createRequestForm.js
https://jira.adeo.no/browse/TOLK-191
Fjernet rødt kryss med "Slett"-tekst. Lagt filer som blir lastet opp i en ul-tag, som leser "Liste over filer", før den navngir alle filer og slett-knappen.
Merk: Når bruker laster opp fil og blir automatisk navigert tilbake til nettleser fra filutforsker vil skjermleser lese opp informasjon fra Google Chrome nivå, og ikke kun den fokuserte checkboxen.
> TOLK-191 UU

- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.html
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.css
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js
- Viser bekreftelse/error til bruker ved sending av interesse for å unngå forvirring om scriptet f.eks. skulle returnere error og stoppe.
- Meld interesse knapp er nå disabled inntil én eller flere sjekkbokser er valgt, slik at bruken av knappen ikke kan misforstås.
- Fikset problem ved at ingen detaljer eller kommentarfelt vises. Var pga. recordMap ikke var i sync med records og nettleser etter at man har filtrert/sendt inn interesse på et oppdrag som gjør at lista blir endret (prøvde å hente ID til en record som ikke var i lista).
- Filtrering for åpne oppdrag lagres nå i sesjonens tab, slik at den bevares ved refresh og ved bruk av tilbakeknapp på mus (som forårsaker refresh). 
**Note: Filter for forrige tab lagres ikke om man går inn i ny tab og endrer filter der uten å gå inn i en …
> Frilans bugs

- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.html
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
- force-app/main/userCommunity/lwc/hot_home/hot_home.js
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.html
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js
- Filters blir nå lagra når man navigerer rundt på tabs. Eneste gangen filter blir resatt på andre tabs er når man melder interesse på et oppdrag i Ledige Oppdrag tabben. Det virker som at det som blir lagret i sesjonen blir nullet ut når man submitter. Prøvd med localStorage og det fungerer heller ikke, så usikker på nøyaktig hva som skjer.
> fix to filter storage and minor fixes

- force-app/main/userCommunity/lwc/hot_userContactInformation/hot_userContactInformation.css
- force-app/main/userCommunity/lwc/hot_userContactInformation/hot_userContactInformation.html
- force-app/main/userCommunity/lwc/hot_userContactInformation/hot_userContactInformation.js
- force-app/main/userCommunity/lwc/hot_userInformation/hot_userInformation.css
- force-app/main/userCommunity/lwc/hot_userInformation/hot_userInformation.html
- force-app/main/userCommunity/lwc/hot_userInformation/hot_userInformation.js
https://jira.adeo.no/browse/TOLK-2022
**Hva er gjort:**
Brødsmulestien som var langt uti huttiheita til venstre er nå sentrert sammen med de andre boksene på midten slik at alle sidene ser like ut. Måten brødsmulestien er laget på er også byttet ut.
Det er også lagt tilbakeknapp slik at bruker kan trykke seg tilbake til forsiden. 
**Testing:**
- Lag community + tolkbruker.
- Gå inn på Min side. 
- Sjekk at brødsmulestien ser lik ut på de andre sidene og sjekk at du kommer deg til forsiden ved å trykke "Tolketjenesten". 
- Gå inn på Min side igjen og sjekk at tilbakeknappen ligger fint og at du kommer deg til forsiden når du trykker på Tilbake. 
- Sjekk at alt ser bra ut på mobil.
> Tolk 2022 - sentrere brødsmulesti og legge til tilbakeknapp min side

- force-app/main/fslStatusTransition/classes/HOT_WorkOrderLineItemStatusHandler.cls
https://jira.adeo.no/browse/TOLK-2158
Om det er opprettet en arbeidsordre med 2 oppdrag, det ene settes til Avlyst og det andre settes til Udekket, status ute hos bestiller viser "Under behandling".
Avlyst+Udekket må gi statusen "Ikke ledig tolk" hos bestiller.
Når en bestilling har flere oppdrag (altså flere tolker), vil bestillingen få status "Ikke ledig tolk" om alle statusene til oppdrag er fylt ut, med en eller flere av både Cancelled og Cannot Complete.
> Tolk 2158 - Feil i statusflyt ved ikke ledige tolker

- force-app/main/userCommunity/classes/HOT_RequestListController.cls
- force-app/main/userCommunity/classes/HOT_RequestListControllerTest.cls
- force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js
https://jira.adeo.no/browse/TOLK-2185
Nå vil ikke oppdrag som har en passert starttid bli satt som avlyst når man avlyser en seriebestilling.
> Tolk 2185 - ikke kunne avlyse oppdrag fra fortiden serie

- force-app/main/fslStatusTransition/classes/HOT_RequestStatusHandler.cls
https://jira.adeo.no/browse/TOLK-2191
Nå vil ikke oppdrag som har startet få endret status (til avlyst) når formidler avlyser seriebestilling.
> Tolk 2191 - feil når formidler avlyser serie

- force-app/main/fslStatusTransition/classes/HOT_RequestStatusHandler.cls
- force-app/main/triggers/classes/HOT_RequestHandlerTest.cls
https://jira.adeo.no/browse/TOLK-2125
Som formidler ønsker jeg at status på WO og SA skal oppdatere seg om F settes til status Udekket.
Om alle Arbeidsordrer og Oppdrag har status Åpen eller Frigitt til frilanstolk, skal formidler kunne sette Forespørselen til Udekket, hvor da status på arbeidsordre(r) og oppdrag automatisk oppdateres.
> Tolk 2125 - Endre status på forespørsel til udekket når alle oppdrag er frigitt til frilans eller alle arbeidsordre er åpen

- force-app/main/freelanceCommunity/classes/HOT_InterestedResourcesListController.cls
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.css
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.html
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.css
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.css
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.html
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js
https://jira.adeo.no/browse/TOLK-2187
Nå inkludert filene :)
Hva som er gjort:
Det er laget popup overlay til alle listene til frilanstolk. Når frilanstolk trykker inn på et oppdrag i listene skal h@n ikke miste skjermposisjonen sin. Beholder alle sine tidligere knapper.
OBS: Det går ikke an å trykke på tilbaketrekk interesse inne på påmeldte oppdrag, med mindre du ikke har endret språk på scratchorg til norsk og lagt inn oversettelse.
Testing:
Sjekk at alle lister vises som de skal når de ikke inneholder oppdrag.
Lag oppdrag til listene og trykk inn på oppdragene.
Sjekk at alle funksjoner fungerer som de skal.
FRA:
TIL:
> Tolk 2187 v2- Popup vindu med informasjon på alle listene for frilanstolk. Nå inkludert filene :)

- force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.js
I utgangspunktet en fiks på at fokus ikke blir satt på toppen når "Fyll ut mer informasjon" velges i bestillingsskjemaet pga bruk av renderedCallback(). Flyttet til connectedCallback() i stedet.
Bonus-fix: Setter fokus på h2 i bestillingsskjema i stedet for helt på topp. Man slipper da å tabbe seg gjennom hele livet.
Testes jo i community ved tabbe seg gjennom en bestilling.
> Bestillingsskjema fix --> master

- force-app/main/freelanceCommunity/classes/HOT_InterestedResourcesListController.cls
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
Fikset sånn at samtalen nullstilles hver gang når man åpner opp et annet oppdrag, og at det er riktig tidssone når bruker sender melding
> Samtale på påmeldte oppdrag med riktig tid ved innsending og samtalevisning

- force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
- force-app/main/triggers/classes/HOT_WorkOrderHandler.cls
Problemet er at `recipients` inneholder verdien `null` og dermed ikke er tom, så den går videre og prøver å opprette et varsel. La til en sjekk på om `userIdByAccountId.get(wo.AccountId)` faktisk returnerer en Id.
> Fikser problemet med varsler på arbeidsordrer og oppdrag uten bruker

- force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
Ser ut som det har sammenheng med oppdrag som ikke er knyttet til bruker.
Følgene spørring som feiler: `List<User> users = [SELECT Id, AccountId FROM User WHERE AccountId IN :accountIds];`
```
11:00:03.527 (5529194588)|FATAL_ERROR|System.LimitException: Too many query rows: 50001
Class.HOT_ServiceAppointmentNotification.notifyUserOnAddedResource: line 323, column 1
Class.HOT_ServiceAppointmentNotification.resourceServiceAppointmentChanged: line 23, column 1
Class.HOT_ServiceAppointmentHandler.onAfterUpdate: line 405, column 1
Class.MyTriggers.run: line 620, column 1
Class.MyTriggers.run: line 567, column 1
Class.MyTriggers.run: line 143, column 1
Trigger.ServiceAppointmentTrigger: line 11, column 1
```
Har lagt inn et filter som fjerner de oppdragene som ikke er knytte til bruker.
Det ser …
> TOLK-2236: Fiks på at formidler får ikke endre status i listevisninger

- scripts/bat/newScratchOrg.bat
- scripts/bat/newScratchOrgMac
Vi har hatt noen deprecation-warnings i newScratchOrg-scriptene våre. Disse er nå endret til sine oppdaterte kall.
force:package:install har blitt endret til package:install
--publishwait har blitt endret til --publish-wait
--permsetname har blitt endret til --perm-set-name
force:community:publish har blitt endret til community:publish
force:apex:execute har blitt endret til apex run
> Endret utdaterte kall i newScratchOrg-scriptene

- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.css
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.css
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.css
- force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.css
https://jira.adeo.no/browse/TOLK-2237
Fikset slik at ikke informasjon om oppdraget blir splittet til ny linje pga det var padding på rundt 10 meter på hver side av info tekstene. 
Og det er full bredde på popup når tolkebruker eller bestiller skal avlyse oppdrag.
Skal ikke påvirke desktop.
> Tolk 2237 - full bredde på avlys popup på mobil + frilanstolk lister på mobil

- force-app/main/triggers/classes/HOT_ServiceResourceHandler.cls
________________________________________
Fra: ApexApplication <[info@emea.salesforce.com](mailto:info@emea.salesforce.com)>
Sendt: torsdag 13. april 2023 14:46:54 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Til: Fosli, Carl Huseby
Emne: Developer script exception from NAV : 'HOT_ServiceResourceHandler' for job id '7077U000022EPZd' : **SObject row was retrieved via SOQL without querying the requested field: User.MiddleName**
Apex script unhandled exception by user/organization: 0052o000009WHXx/00D2o000000aANV
Failed to invoke future method 'public static void createServiceResourceFuture(List<Id>)' on class 'HOT_ServiceResourceHandler' for job id '7077U000022EPZd'
caused by: System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: …
> TOLK-2242: Update HOT_ServiceResourceHandler.cls --> master Missing MiddleName

- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
Sjekk at den husker checkboxvalgene ved skifte av liste og ved refresh på LEDIGE OPPDRAG
Når man går helt ut til startsiden og inn på listene igjen skal den IKKE huske.
> Husker checkboxvalg

- force-app/main/default/objectTranslations/HOT_Request__c-no/IsOrdererWantStatusUpdateOnSMS__c.fieldTranslation-meta.xml
- force-app/main/default/objectTranslations/HOT_Request__c-no/IsReminderSMS__c.fieldTranslation-meta.xml
- force-app/main/default/objects/HOT_Request__c/fields/IsOrdererWantStatusUpdateOnSMS__c.field-meta.xml
- force-app/main/default/objects/HOT_Request__c/fields/IsReminderSMS__c.field-meta.xml
- sfdx-project.json
Test: 
Gå inn på en request og sjekk feltene: "Order Status SMS?" og "Reminder SMS?" har riktige ordlyder,
* "Order Status SMS?" sin ordlyd skal være: 
"Når denne er huket av, vil bestiller på vegne av bruker få varsel når status på bestillingen endres."
* "Reminder SMS?" skal være: 
"Når denne er huket av, vil bruker få påminnelse dagen før det finner sted. Om bruker har reservert seg for varsler, vil de ikke motta denne påminnelsen."
> Endret ordlyder som inneholder sms til å være mer passende ettersom vi i har støtte for flere varslingskanaler.

- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/columns.js
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
- force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
ST snakket med dem og de ønsker ikke automatikk. Dermed må de manuelt merke om et oppdrag haster eller ikke.
Sjekk at det ikke finnes noe automatikk på feltet. Lag et oppdrag og på SA kan du merke et oppdrag som "urgent". Frigjør til frilans og på frilans ledige oppdrag skal det være et ikon om det er merket som haster. 
**OPPRINNELIG:**
https://github.com/navikt/crm-hot/pull/1557/files#diff-f0cfa4c6bd92609745948efef5843e4880cf70fa48dac8960d484fd778eb0480
**KOMMENTERT UT FOR Å FJERNE AUTOMATIKK:**
https://github.com/navikt/crm-hot/pull/1568/files
> Merke at et oppdrag haster.

- force-app/main/dialogue/classes/HOT_MessageHelper.cls
- force-app/main/dialogue/classes/HOT_MessageHelperTest.cls
- force-app/main/dialogue/classes/HOT_ThreadHandler.cls
- force-app/main/dialogue/classes/HOT_ThreadHandlerTest.cls
- force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.js
- force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.html
- force-app/main/dialogue/external-components/lwc/hot_threadList/hot_threadList.js
- force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.html
- force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.js
- force-app/main/freelanceCommunity/classes/HOT_MyServiceAppointmentListController.cls
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.html
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
Når tolk er tildelt oppdraget vil oppdraget ligge på "mine oppdrag" listen. Her kan frilanstolk nå velge mellom snakke med tolk og bruker, eller bare medtolker. Samme med formidler.
**KUN 1 TOLK:**
Sjekk at frilanstolk bare kan starte samtale med medtolk om det finnes flere enn 1 tolk på oppdraget. Ellers vil knappen være disablet. Samme med formidler; Skal ikke kunne trykke samtale med medtolk med mindre det er mer enn 1 tolk.
**FLERE TOLKER PÅ OPPDRAGET:**
Som formidler: på wo trykk samtale med tolk og bruker, og lag en ny samtale med medtolk. **Husk å skriv meldinger.**
Logg inn i community og sjekk at samtalen du skrev mellom tolk-bruker dukker opp hos både tolk og bruker. Og samtalen du startet mellom medtolk kun dukket opp mellom medtolk.
Slett trådene.
Som frilanstolk: mine oppdrag …
> Ny dialog mellom medtolker

- force-app/main/default/objectTranslations/ServiceAppointment-no/HOT_IsUrgent__c.fieldTranslation-meta.xml
- force-app/main/default/objects/ServiceAppointment/fields/HOT_IsUrgent__c.field-meta.xml
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
Sjekk at det står 
"Høyt prioritert oppdrag?" på feltet på SA på formidler på norsk.
"Høyt prioritert" på oppdrag som er merket for frilanstolker.
> Endret tekst på høyt prioriterte oppdrag

- force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.html
- force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
Det er ikke lenger ønskelig med samtale bruker og bestiller da det kunne føre til at meldinger som ikke var ment til å gå gjennom NAV kunne bli sendt her. Eks: meldinger mellom tolkebruker - lege/sykehus osv. 
ST var enig om å bare skjule knappene i tilfelle det skulle være ønskelig senere.
> Ingen samtale mellom bruker og bestiller

- force-app/main/triggers/classes/HOT_InterestedResourceHandler.cls
- force-app/main/triggers/classes/HOT_InterestedResourceHandlerTest.cls
- force-app/main/wageClaim/classes/HOT_WageClaimServiceTest.cls
https://jira.adeo.no/browse/TOLK-1645
Når frilanstolk melder interesse til et oppdrag samtidig som formidler tildeler en annen tolk oppdraget, vil IR nå få automatisk status 'Ikke tildelt deg'
TEST:
Lag et oppdrag og frigi til frilans.
Logg inn i community og gå til ledige oppdrag liste.
Imens gå som formidler i salesforce og tildel oppdraget til en anne tolk.
I community så trykk meld interesse på det samme oppdraget
Sjekk nå at status på denne nye interesserte ressursen fikk status Ikke tildelt deg
> TOLK 1645 - statusflyt interessert ressurs ved påmelding samtidig som tildeling av annen ressurs

- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
https://jira.adeo.no/browse/TOLK-2275
**FEIL:** _Som frilanstolk i uathot:
Går du fra forsiden, til oppdrag, trykker tilbake til forsiden, og så trykker oppdrag igjen loader bare listen evig og ingenting kommer opp_
Viste seg å være at sessionStorage var undefined når man gikk inn på siden på nytt.
> TOLK 2275 : Fikser feil som gav evigload på Ledig oppdrag listen

- force-app/main/default/flows/HOT_RegisterWantedServiceResource.flow-meta.xml
- force-app/main/freelanceCommunity/classes/HOT_OpenServiceAppointmentListController.cls
- force-app/main/freelanceCommunity/classes/HOT_wantedSRListController.cls
https://jira.adeo.no/browse/TOLK-2303
Om formidlere registrerer ønsket ressurs på oppdrag som tilhører samme arbeidsorder (som er unødvendig), så blir det bare kaos når frilanstolken melder interesse. Blir duplikater og masse styr. Frilanstolk trenger uansett KUN å melde interesse for det ene oppdraget.
-------------------------------
Så når ønsket ressurs skal registrers nå vil formidler få beskjed at ikke den kan registreres fordi det finnes allerede en IR med den tolken på et oppdrag tilhørende samme arbeidsordre. 
I tillegg endret jeg teksten som stod gjennom flowen. Det ble ikke endret sist etter ønskene.
> TOLK-2303 : Fikser et kommende problem angående formidlers bruk av ønsket oppdrag og endrer gammel tekst

- force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js
"Fått melding fra Trøndelag nå på morgenen at bruker ikke har fått avlyst en bestilling via tolkebestillingsløsningen.  Ser at vi har feil i UATHOT at avlys/avlys serie-knappen er grået ut.  Både det i prod og i uat er bestilling for seg selv."
> Knapp blir nå resatt når bruker går inn på annet oppdrag -- > Master

- force-app/main/sms/classes/HOT_ReminderSMSService.cls
https://jira.adeo.no/browse/TOLK-2377
Siden det ble lagt til @Future på metoden HOT_MessagesNotification.NotifyInterpreter()  (https://github.com/navikt/crm-hot/pull/1843) og det allerede var @Future på metoden HOT_ReminderSMSService.sendSMSOnNewMessageInterpreter() første dette til at man fikk en feilmelding. Kan ikke kalle en future-metode fra en annen future-metode. Løste dette ved å fjerne @Future fra den siste (siden den da allerede er i en future-metode).
> TOLK-2377- Frilanstolk får ikke SMS varsel ved ny melding

- force-app/main/wageClaim/classes/HOT_WageClaimHandler.cls
Når frilanstolk/formidler trekker tilbake tilgjengelighet for et oppdrag skal det ikke dannes lønnskrav/skift i ressursplanleggeren.
Det har visst vært en feil hvor metoden lå i onBeforeInsert, og metoden skulle bruke Id til wc. Måtte flytte den til onAfterInsert
> TOLK-2190 : Lønnskrav (skift) skal forsvinne når tilgjengelighet tilbaketrekkes

- force-app/main/default/permissionsets/HOT_Tolk_Ansatt.permissionset-meta.xml
Siden metoden sjekker på visse felt før den markerer samtalen som lest, så er disse feltene tomme i tilfellene hvor ansatte startet samtaler fordi de ikke hadde tilgang
[TOLK-2453](https://jira.adeo.no/browse/TOLK-2453)
> TOLK 2454 : Samtaler forsvinner ikke fra Ulest-listene til formidler

- force-app/main/dialogue/classes/HOT_MessageHelper.cls
- force-app/main/dialogue/classes/HOT_ThreadHandler.cls
- force-app/main/dialogue/internal-components/lwc/hot_messagingMessageComponent/hot_messagingMessageComponent.html
Ettersom vi for en tid siden endret slik at når tolken avlyste og fikk status avlyst av tolk, og for at vi skal kunne sette participant feltet når det skal startes en samtale med tolk etter at det er avlyst på en eller anne måte, må vi endre slik at det kan kun startes samtale fra SA når tolken er tildelt/reservert. Ellers må det gjøres via IR.
Har måtte endre litt funksjonalitet. Om tolken er tildelt oppdraget og det på noen måte avlyses;
- Om det finnes samtale fra før det avlyses må får man beskjed om å fortsette samtalen på SA. (den blir som vanlig overført til IR når ny tolk tildeles)
- Om det lages en samtale etter at det er avlyst må det lages på IR. 
> Endring på dialoglønsingen

- force-app/main/accessControl/classes/HOT_ThreadAccessHandler.cls
Iden koden før var brukt i en future, så sendte man bare med id. Nå kan man sende med hele objektet, og trenger da ikke SOQL-spørringen i det hele tatt.
> TOLK-2479: Fjernet SOQL-spørringen

- force-app/main/dialogue/classes/HOT_MessageHelper.cls
Ansatt tolk kunne ikke markere meldinger som lest om oppdraget de hadde samtale på var avlyst. Fjernet sjekken om tilgang og heller sjekker om user id finnes i participants feltet på tråd før man markerer tråden som lest
> TOLK-2758 : Markere samtale som lest ansatt tolker

- force-app/main/default/objects/ServiceAppointment/validationRules/RemoveARBeforeResettingStatus.validationRule-meta.xml
Added new Validation rule for Service Appointment. If a resource is assigned, the user will not be allowed to reset the status back to default
> TOLK-2830: Create RemoveARBeforeResettingStatus.validationRule-meta.xml

- force-app/main/dialogue/external-components/lwc/hot_messagingCommunityThreadViewer/hot_messagingCommunityThreadViewer.js
- force-app/main/freelanceCalendar/lwc/hot_calendar_wrap/hot_calendar_wrap.css
- force-app/main/freelanceCalendar/lwc/hot_calendar_wrap/hot_calendar_wrap.html
- force-app/main/freelanceCalendar/lwc/hot_calendar_wrap/hot_calendar_wrap.js
- force-app/main/freelanceCommunity/classes/lwc/hot_informationModal/hot_informationModal.js
- force-app/main/freelanceCommunity/lwc/hot_frilanstolkThreadList/hot_frilanstolkThreadList.js
- force-app/main/freelanceCommunity/lwc/hot_interestedResourcesList/hot_interestedResourcesList.js
- force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
- force-app/main/freelanceCommunity/lwc/hot_openServiceAppointments/hot_openServiceAppointments.js
- force-app/main/freelanceCommunity/lwc/hot_wantedServiceAppointmentsList/hot_wantedServiceAppointmentsList.js
- force-app/main/userCommunity/lwc/datetimeFormatterNorwegianTime/datetimeFormatterNorwegianTime.js
- force-app/main/userCommunity/lwc/datetimeFormatterNorwegianTime/datetimeFormatterNorwegianTime.js-meta.xml
- force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.js
- force-app/main/wageClaim/lwc/hot_wageClaimList/hot_wageClaimList.js
Viser alltid norske tider for FRILANS på:
-Ledige oppdrag liste
-Påmeldte oppdrag liste
-Mine oppdrag liste
-Ledig på lønn liste
-Ønsket til oppdrag liste
- Oppdrag-start tidspunkt i "mine samtaler som frilans" meldingslister.
- Oppdragsdetaljer når man trykker gå til bestilling inne på en samtale.
Viser alltid norske tider for BRUKER på:
- Mine bestillinger
**NB!** Vises ikke norske tider i kalender for frilans, så den skjules når brukeren befinner seg utenfor norsk tiddsone
> TOLK-2804 : Alltid vise norske tidssoner v2
